---
default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push
  - post-checkout

default_stages:
  - pre-commit

repos:
  # Generic hooks that apply to a lot of files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

      # The following only check that the files are parseable and does _not_
      # modify the formatting.
      - id: check-toml
      - id: check-xml

  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.17.0
    hooks:
      - id: yamlfix

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      # As above, this only checks for valid JSON files. This implementation
      # allows for comments within JSON files.
      - id: check-json5

  - repo: https://github.com/biomejs/pre-commit
    rev: v0.5.0
    hooks:
      - id: biome-check
        additional_dependencies:
          - '@biomejs/biome@1.9.4'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
      - id: ruff-format

  - repo: https://github.com/crate-ci/committed
    rev: v1.1.1
    hooks:
      - id: committed

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        exclude: |
          (?x)^(
            src/pypacter/.*\.md
          )

  - repo: https://github.com/crate-ci/typos
    rev: v1.28.1
    hooks:
      - id: typos

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args:
          - --external-sources

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.9.0-1
    hooks:
      - id: shfmt

  - repo: local
    hooks:
      # Mypy is difficult to run in pre-commit's isolated environment as it
      # needs to be able to find dependencies.
      - id: mypy
        name: mypy
        entry: hatch run mypy
        language: system
        types:
          - python
        stages:
          - pre-push
